---
- name: "Creating Hetzner Network"
  hetzner.hcloud.hcloud_network:
    api_token: "{{ hcloud_api_token }}"
    name: "{{ hcloud_network_name }}"
    delete_protection: "{{ hcloud_network_delete_protection }}"
    expose_routes_to_vswitch: "{{ hcloud_network_expose_routes_to_vswitch }}"
    ip_range: "{{ hcloud_network_ip_range }}"
    labels: "{{ hcloud_network_labels | default(omit) }}"
    state: present
  delegate_to: localhost
  when: hcloud_network_state == 'present'

- name: "Creating Hetzner Subnetwork"
  hetzner.hcloud.hcloud_subnetwork:
    api_token: "{{ hcloud_api_token }}"
    network: "{{ hcloud_network_name }}"
    network_zone: "{{ hcloud_network_zone }}"
    ip_range: "{{ hcloud_network_ip_range }}"
    type: "{{ hcloud_network_type | default('cloud') }}"
    vswitch_id: "{{ hcloud_network_vswitch_id | default(omit) }}"
    state: present
  delegate_to: localhost
  when: hcloud_network_state == 'present'

- name: "Deleting Hetzner Subnetwork"
  hetzner.hcloud.hcloud_subnetwork:
    api_token: "{{ hcloud_api_token }}"
    network: "{{ hcloud_network_name }}"
    network_zone: "{{ hcloud_network_zone }}"
    ip_range: "{{ hcloud_network_ip_range }}"
    type: "{{ hcloud_network_type }}"
    state: absent
  delegate_to: localhost
  when: hcloud_network_state == 'absent'

- name: "Deleting Hetzner Network"
  hetzner.hcloud.hcloud_network:
    api_token: "{{ hcloud_api_token }}"
    name: "{{ hcloud_network_name }}"
    state: absent
  delegate_to: localhost
  when: hcloud_network_state == 'absent'
